#!/bin/bash
##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
#
# NAME :        config_cream_emies_scratch_reinstall
#
# DESCRIPTION : This function configures the Cream EMI-ES service
#
# AUTHORS :     massimo.sgaravatto@pd.infn.it
#
# YAIM MODULE:  glite.yaim.cream-ce

##############################################################################

function config_cream_emies_scratch_reinstall_check () {
  requires $1 USE_EMIES
}

function config_cream_emies_scratch_reinstall_setenv () {
 yaimlog DEBUG "This function doesn't set any environment variables"
}

function config_cream_emies_scratch_reinstall () {

if [ ${USE_EMIES} = false ]; then
  yaimlog DEBUG "Removing EMI-ES, if installed"
  
  rm -Rf ${CATALINA_HOME}/webapps/ce-cream-es
  if [ -e ${CATALINA_HOME}/conf/Catalina/localhost/ce-cream-es.xml ] ; then
    rm -f ${CATALINA_HOME}/conf/Catalina/localhost/ce-cream-es.xml
  fi

  return 0
fi


yaimlog DEBUG "Reinstall EMI-ES if needed"

ESLIBDIR=${CATALINA_HOME}/webapps/ce-cream-es/WEB-INF/lib

if [ -d ${CATALINA_HOME}/webapps/ce-cream-es ] ; then
    return 0
fi

cp -R /usr/share/axis2/webapp ${CATALINA_HOME}/webapps/ce-cream-es

[ -h ${ESLIBDIR}/cedar.jar ] || ln -s /usr/share/java/jclassads/cedar.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/classad.jar ] || ln -s /usr/share/java/jclassads/classad.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/bcprov.jar ] || ln -s /usr/share/java/bcprov.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/bcmail.jar ] || ln -s /usr/share/java/bcmail.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/argus-pep-api-java.jar ] || ln -s /usr/share/java/argus-pep-api-java.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/argus-pep-common.jar ] || ln -s /usr/share/java/argus-pep-common.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/canl.jar ] || ln -s /usr/share/java/canl.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/voms-api-java3.jar ] || ln -s /usr/share/java/voms-api-java3.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/glite-jobid-api-java.jar ] || ln -s /usr/share/java/glite-jobid-api-java.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/glite-lb-client-java.jar ] || ln -s /usr/share/java/glite-lb-client-java.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/glite-ce-common-java.jar ] || ln -s /usr/share/java/glite-ce-common-java.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/glite-ce-cream-api-java.jar ] || ln -s /usr/share/java/glite-ce-cream-api-java.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/glite-ce-cream-blahExecutor.jar ] || ln -s /usr/share/java/glite-ce-cream-blahExecutor.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/glite-ce-cream-core.jar ] || ln -s /usr/share/java/glite-ce-cream-core.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/glite-ce-cream-delegationExecutor.jar ] || ln -s /usr/share/java/glite-ce-cream-delegationExecutor.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/glite-ce-cream-es-skeleton.jar ] || ln -s /usr/share/java/glite-ce-cream-es-skeleton.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/glite-ce-delegation-skeleton.jar ] || ln -s /usr/share/java/glite-ce-delegation-skeleton.jar ${ESLIBDIR}
[ -h ${ESLIBDIR}/glite-jdl-api-java.jar ] || ln -s /usr/share/java/glite-jdl-api-java.jar ${ESLIBDIR}

# set allowLinking option for tomcat6
if [ ! -d ${CATALINA_HOME}/webapps/ce-cream-es/META-INF ] ; then
  mkdir ${CATALINA_HOME}/webapps/ce-cream-es/META-INF
  echo '<Context override="true" allowLinking="true"></Context>' > ${CATALINA_HOME}/webapps/ce-cream-es/META-INF/context.xml
fi

ln -sf /usr/share/glite-ce-cream/modules/glite-ce-cream-authorization.mar ${CATALINA_HOME}/webapps/ce-cream-es/WEB-INF/modules
find ${CATALINA_HOME}/webapps/ce-cream-es/WEB-INF/modules -name *.mar -exec basename \{\} \; > ${CATALINA_HOME}/webapps/ce-cream-es/WEB-INF/modules/modules.list
  
ln -sf /usr/share/glite-ce-cream/services/glite-ce-cream-es.aar ${CATALINA_HOME}/webapps/ce-cream-es/WEB-INF/services
find ${CATALINA_HOME}/webapps/ce-cream-es/WEB-INF/services -name *.aar -exec basename \{\} \; > ${CATALINA_HOME}/webapps/ce-cream-es/WEB-INF/services/services.list

# cannot use symlinks for the following files, copy is needed:
cp -f /etc/glite-ce-cream-es/web.xml ${CATALINA_HOME}/webapps/ce-cream-es/WEB-INF/
cp -f /etc/glite-ce-cream-es/axis2.xml ${CATALINA_HOME}/webapps/ce-cream-es/WEB-INF/conf
chmod 600 ${CATALINA_HOME}/webapps/ce-cream-es/WEB-INF/conf/axis2.xml
chown tomcat.tomcat ${CATALINA_HOME}/webapps/ce-cream-es/WEB-INF/conf/axis2.xml

return 0


}
